language: go

go:
  - 1.x

notifications:
  email:
    recipients:
        - eric.elsken@gmail.com
    on_success: change
    on_failure: change

env:
  - GO111MODULE=on

install:
  - ./bin/travis/install

script:
  - ./bin/travis/test-coverage

after_success:
  - ./bin/coveralls/push
