language: go

go:
  - 1.x

notifications:
  email:
    recipients:
        - eric.elsken@gmail.com
    on_success: change
    on_failure: change

env:
  global:
    - GO111MODULE=on
    # COVERALLS_TOKEN
    - secure: "i8j1qYXRo8PW/lVRsM4pFJbleA2xCygZhQ+TEzuG8JuM40Kj4eUQ5zeOalUN4fuBVpKBL+RLoi+aU+axhgVTyKWDjGaB8ckRuehFdMeOuRaw+bMQGzjWWyNF4lHfViT3vCLrcIK3dZyZMTestB1Nnhl6Rw6089GUkRSX7hS3Ys4zhyrjK5rz3z9I4C+vtft0BnZgLUtVG2THmCae8lt3iZykmfLqn9sg0OpIMGRwqTjRIrG00lt3MxNy3eAURMv5kKciGKRhlUDOgVOnMt/QfHpFHsdnsI+8T0eP481N6uvj4GDXH58FNiv7PM30La5NVyGq3D3cwHK8GXloZf+02Pb53oL4WQR1QoG736RNYAYeXOEM/L07s0cNIg+ZslTR8nTk1t6V4njwaeGhrexvmJOtIsTPLMEy1omxFcqUjrx1aWK2vwGPcVdxFKxoaM+8CQyBoHen2q51CH+j9m5f0euTs/Rdfq6hKdtEgnq+Q/Rw2xYW+9UyIGUqfuUawFHppeaWZ/6tvRDfss4XPOw+x3Y9NMhop0rNM5kaTDzF78azyTOeN1Nsy6slW4CLZ/bb0DWq6fkqVF/n9OkNBO17zi2GCnbyGHYk2n4OB2QB68tQekfc57AS/RDrT1pwD+J8jvbX7ysXJ3UvNljNhUvRRytOCJzOqJ7+PkHYPHBL94U="

install:
  - ./bin/travis/install

script:
  - ./bin/travis/test-coverage

after_success:
  - ./bin/coveralls/push
