language: go

go:
  - 1.x

notifications:
  email:
    recipients:
        - eric.elsken@gmail.com
    on_success: change
    on_failure: change

install:
  - ./bin/travis/install

script:
  - ./bin/travis/test_coverage.sh

after_success:
  - ./bin/coveralls/push.sh
